FROM node:23-alpine3.21 AS deps
WORKDIR /app
LABEL maintainer="filipe.costa"

ENV NODE_ENV=production
# Install dependencies based on the preferred package manager
COPY package*.json ./
RUN npm ci;

# 2. Rebuild the source code only when needed
FROM node:23-alpine3.21 AS builder
WORKDIR /app

COPY tsconfig*.json ./
COPY package*.json ./
COPY nest-cli.json ./
COPY src ./src
RUN npm ci;

ENV NODE_ENV=production
RUN npm run build;

# 3. Production image
FROM node:23-alpine3.21 AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 app
RUN adduser --system --uid 1001 app

# Production dependencies
COPY --from=deps --chown=app:app /app/package.json ./package.json
COPY --from=deps --chown=app:app /app/node_modules ./node_modules
# Production build
COPY --from=builder --chown=app:app /app/dist ./dist

USER app
EXPOSE 3000
ENV PORT=3000

CMD ["node", "dist/main"]